<?php

// @codingStandardsIgnoreFile

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php
$post=$this->getRequest();
if(isset($post)){
$msg=/* @escapeNotVerified */ __('No Result Found. <a href="'.$this->getUrl('sales/order/history').'">Reset My Orders</a>');
}else{
    $msg=/* @escapeNotVerified */ __('You have placed no orders.');

}
?>

<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history co-search">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col order"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                    <th scope="col" class="col product"><?= /* @escapeNotVerified */ __('products') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                </tr>
                <tr>
                    <form method='get' >
                    <th scope="col" class="col order"><input type="text" name="orderid" placeholder="Search Order No" value="<?= $this->getRequest()->getParam('orderid')?>" />
                    </th>
                    <th scope="col" class="col products"><input type="text" placeholder="Search SKU"  name="sku" value="<?= $this->getRequest()->getParam('sku')?>" /></th>
                    <th scope="col" class="col date" id="calendar_inputField">
                        <div class="form-date">
                            <input type="text" placeholder="From" id="date-from" name="from_date" value="<?= $this->getRequest()->getParam('from_date')?>"/>
                        </div>
                        <div class="to-date">
                            <input type="text" id="date-to" name="to_date" placeholder="To" value="<?= $this->getRequest()->getParam('to_date')?>"/>
                        </div>
                    </th>
                    <th scope="col" class="col shipping"><input type="text"  disabled /></th>
                    <th scope="col" class="col total"><input type="text" disabled/></th>
                    <th scope="col" class="col status"><input type="text" disabled /></th>
                    <th scope="col" class="col actions"><button type="submit" value="Filter">Filter</button></th>
                    </form>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col order"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col products"><?= /* @escapeNotVerified */ $block->getProductName($_order) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <button><?= /* @escapeNotVerified */ __('View Order') ?></button>
                            </a>
                            <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <button><?= /* @escapeNotVerified */ __('Reorder') ?></button>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $msg ?></span></div>
<?php endif ?>

<script>
        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
            $("#calendar_inputField").dateRange({
                buttonText: 'Select Date',
        from: {
            id: 'date-from'
        },
        to: {
            id: 'date-to'
        }
            });
        });
</script>